# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8b27514874f0a2d3b6b0a47042b187782053b23486a9c8cbd5a0d4ff140649a4a8a4bd794cfe6a68530e5512394d5516e0481b11926a9a9e2574578b9e666c

test:
  secret_key_base: dc5857fefb5bc451b572879c34bd84ad305261f2b9a90d5f9ce60ea0810e68fc83a22241a6168064febf9e6bc1d2bd7e3d479c44dc49831588b938582a9873c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
